env:
 - OPTIONS="-DCMAKE_BUILD_TYPE=Release"
 - OPTIONS="-DCMAKE_BUILD_TYPE=Debug"

before_script:
  - sudo apt-get update > /dev/null
  - sudo apt-get install cmake swig2.0 liblua5.1-0-dev python-dev  > /dev/null

script:
  - cmake . $OPTIONS
  - make ouroboros_test
  - ./test/ouroboros_test
  - cd ./test
  - ./oldscript_test
  - cd ..

notifications:
  email:
      - kazuo256@gmail.com
      - rewasvat@gmail.com
