language: cpp

compiler:
  - gcc

cache: apt

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository -y ppa:henriquegemignani/uspgamedev
  - sudo apt-get update

install:
  - sudo apt-get install cmake liblua5.1-0-dev python-dev
  - if [ "$CXX" = "g++" ]; then sudo apt-get install --force-yes g++-4.7; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.7" CC="gcc-4.7"; fi

script:
  - cmake .
  - make
  - make ouroboros_test
  - ./test/ouroboros_test
  - make oldscript_test
  - cd ./test
  - ./oldscript_test
  - cd ..
  - make opwig_test
  - ./test/opwig_test
  - make opa_test
  - ./test/opa_test

notifications:
  email:
      - kazuo256@gmail.com
      - rewasvat@gmail.com
      - henrique@gemignani.org
